### ISSUE TITLE
Improve the parser syntax

### ISSUE THREAD

**Issue by TheLubab** [NEARBuilders/bos-workspace#47]
The `/*__@replace:alias__*/` is hard to type and not optimal. Maybe we should switch it to something more concise, easier to write and read with less constraints without conflicting with other code.

We need a syntax that is language agnostic, we want the commands to be parsed in every type of comments one line or multi line, be it in JS, HTML, CSS, JSONC or any language. Using the `@` in js will also help with syntax highlighting.

for example to import a module:
```js
// @alias(hello)
// @import(module)
// @account
/* @alias(hello) */
```
```html
<!-- @alias(hello) -->
```
```css
/* @alias(hello) */
```
```jsonc
// @skip
{}
```

This will break projects using the older syntax, if we choose to implement it we have to support both syntaxes until we remove the old in a future major release.

@elliotBraem, you used `bos-workspace` more than anyone, so what do you think about this? is a an unnecessary change or an improvement?

**Comment by elliotBraem** [comment]
Yeah, glad you've brought this up. 

The current format, including for app account (/*__@appAccount__*/), can be hard to type/remember, as well as, since it is a essentially a comment format, commenting out a code block containing it can lead to a poor experience; it'll comment the first part, uncomment the alias, etc... 

[bos-loader](https://github.com/near/bos-loader)'s replacement strategy recognizes `{REPL_KEY}`, which works pretty well although (I've heard, but not experienced myself) it can cause some issues with syntax highlighting. This is the strategy used by [DevHub](https://github.com/near/neardevhub-widgets) and [Near Discovery](https://github.com/near/near-discovery-components), adopting it would be easiest migration for them if they chose to do it. 

I like using the `@` for syntax highlighting, especially for skip.

**Comment by elliotBraem** [comment]
From conversation and to have parity with bos-loader, we should use ${} for replacements
